version: '3.1'

services:

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - hyper

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 1${DB_PORT}:8080
    depends_on:
      - postgres
    networks:
      - hyper

networks:
  hyper:

volumes:
  pg-data:
