export const GET_ALL_TASKS_REQUEST = "GET_ALL_TASKS_REQUEST";
export const GET_ALL_TASKS_SUCCESS = "GET_ALL_TASKS_SUCCESS";
export const GET_ALL_TASKS_FAILURE = "GET_ALL_TASKS_FAILURE";

export const CREATE_NEW_TASK_REQUEST = "CREATE_A_NEW_TASK_REQUEST";
export const CREATE_NEW_TASK_SUCCESS = "CREATE_A_NEW_TASK_SUCCESS";
export const CREATE_NEW_TASK_FAILURE = "CREATE_A_NEW_TASK_FAILURE";

export const GET_A_TASK_REQUEST = "GET_A_TASK_REQUEST";
export const GET_A_TASK_SUCCESS = "GET_A_TASK_SUCCESS";
export const GET_A_TASK_FAILURE = "GET_A_TASK_FAILURE";

export const DELETE_TASK_REQUEST = "DELETE_A_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_A_TASK_SUCCESS";
export const DELETE_TASK_FAILURE = "DELETE_A_TASK_FAILURE";

export const UPDATE_TASK_REQUEST = "UPDATE_A_TASK_REQUEST";
export const UPDATE_TASK_SUCCESS = "UPDATE_A_TASK_SUCCESS";
export const UPDATE_TASK_FAILURE = "UPDATE_A_TASK_FAILURE";