

export const CREATE_NEW_SUBTASK_REQUEST = "CREATE_A_NEW_SUBTASK_REQUEST";
export const CREATE_NEW_SUBTASK_SUCCESS = "CREATE_A_NEW_SUBTASK_SUCCESS";
export const CREATE_NEW_SUBTASK_FAILURE = "CREATE_A_NEW_SUBTASK_FAILURE";

export const GET_A_SUBTASK_REQUEST = "GET_A_SUBTASK_REQUEST";
export const GET_A_SUBTASK_SUCCESS = "GET_A_SUBTASK_SUCCESS";
export const GET_A_SUBTASK_FAILURE = "GET_A_SUBTASK_FAILURE";

export const DELETE_SUBTASK_REQUEST = "DELETE_A_SUBTASK_REQUEST";
export const DELETE_SUBTASK_SUCCESS = "DELETE_A_SUBTASK_SUCCESS";
export const DELETE_SUBTASK_FAILURE = "DELETE_A_SUBTASK_FAILURE";

export const UPDATE_SUBTASK_REQUEST = "UPDATE_SUBTASK_REQUEST";
export const UPDATE_SUBTASK_SUCCESS = "UPDATE_SUBTASK_SUCCESS";
export const UPDATE_SUBTASK_FAILURE = "UPDATE_SUBTASK_FAILURE";

export const UPDATE_SUBTASK_STATUS_REQUEST = "UPDATE_SUBTASK_STATUS_REQUEST";
export const UPDATE_SUBTASK_STATUS_SUCCESS = "UPDATE_SUBTASK_STATUS_SUCCESS";
export const UPDATE_SUBTASK_STATUS_FAILURE = "UPDATE_SUBTASK_STATUS_FAILURE";

export const GET_ALL_SUBTASKS_BY_TASK_ID_REQUEST = "GET_ALL_SUBTASKS_BY_TASK_ID_REQUEST";
export const GET_ALL_SUBTASKS_BY_TASK_ID_SUCCESS = "GET_ALL_SUBTASKS_BY_TASK_ID_SUCCESS";
export const GET_ALL_SUBTASKS_BY_TASK_ID_FAILURE = "GET_ALL_SUBTASKS_BY_TASK_ID_FAILURE";